### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by bryanberger** [YilianSource/party-js#10]
add to npm

**Comment by YilianSource** [comment]
I'll definitely take a look at this, I've never published an npm package before, thanks for the suggestion!

**Comment by YilianSource** [comment]
@bryanberger I set up the npm package for the project! Unfortunately, the name is currently too similar to an existing package, which hasn't been updated in three years. I will try to resolve the matter with the project owner. I'll let you know here once it's published on npm!

**Comment by YilianSource** [comment]
Alright, the package is now available on npm, @bryanberger! You can install it via:
```js
npm install party-js
```
It will be included in the documentation with #2 and #3.
