### ISSUE TITLE
Emojis support ❤️

### ISSUE THREAD

**Issue by webdeb** [yiliansource/party-js#107]
Hey, I think this is self describing :)
Unfortunately I did't found how this could be done easily.
Should one create svgs/pngs?

I would propose smth like 

```
shapes: ["❤️", "🎉", "🚀"]
```

Or would this work like this?

```ts
party.resolvableShapes["emHeart"] = `<i>❤️</i>`;
party.resolvableShapes["emRocket"] = `<i>🚀</i>`;
...
...
shapes: ["emHeart", "emRocket"]
```

**Comment by yiliansource** [comment]
> Or would this work like this?
> 
> ```
> party.resolvableShapes["emHeart"] = `<i>❤️</i>`;
> party.resolvableShapes["emRocket"] = `<i>🚀</i>`;
> ...
> ...
> shapes: ["emHeart", "emRocket"]
> ```

Hi, that's exactly how it would work!

![image](https://github.com/yiliansource/party-js/assets/41469451/b1761d49-5ac6-43ad-89ee-98a10eee3079)

https://codepen.io/yilian/pen/VwNyGme

**Comment by webdeb** [comment]
Awesome, thank you!
