### ISSUE TITLE
Weird footer.

### ISSUE THREAD

**Issue by harshhhdev** [YilianSource/party-js#15]
Not a huge problem that I have here, it is just something which could be improved or fixed on the party.js [website]

![image](https://user-images.githubusercontent.com/69592270/98294939-bd778880-1f7e-11eb-9032-5ae0c195aa2a.png)

The centering of the "More, GitHub" on the footer is strange. It is neither centered nor is it aligned to a side

The fix I'd like to see for this would be aligning it to the right.

An alternative fix that would also work is centering it, though imo aligning it to the right would look cooler :smile:

**Comment by YilianSource** [comment]
Ah, good catch! I completely glanced over that, because there were 3 columns in the template before (Docs, Blog, More), but I got rid of the blog. I'll mess around with a solution sometime over the next days!
