### ISSUE TITLE
Problems when used as npm package

### ISSUE THREAD

**Issue by zitrone475** [YilianSource/party-js#17]
Hey there,

first of all thanks for your work! I am currently using your libary in Vuejs. But to include it there was really annoying. You are providing an NPM (The Node.js packet manager) package. But there is no export in your script. So in my opinion it is not usable as NPM package. Please consider doing something like:

`export default party`

at the end of your file to enable easy import with something like 

`import party from 'party-js'`.

Thank you in advance!

**Comment by YilianSource** [comment]
Thank you so much for the kind words! Glad you like it.

I'll be completely honest with you, back when I released it as an NPM package I didn't really know how to and just prayed it would work. I'll try to fix it today.

My issue that I would still like to make it use-able as a global script, like you'd have with jQuery or similar. Wouldn't providing an export make that impossible, since you can't import/export outside of a module?

**Comment by zitrone475** [comment]
I think the best way would be to create 2 versions. One for jQuery and one for NPM. For the NPM version, simply adding the "export default party" line at the end should do the trick. Maybe the NPM version also works fine with jquery, then of course you wouldn't have to make 2 versions.

**Comment by YilianSource** [comment]
Alright, I read into the matter a bit. I added UMD support, so now you should be able to import it using AMD, CJS and as a browser global.

Would you do me a favour and check if it works for you now, so we can close this?

**Comment by zitrone475** [comment]
Thank you for the quick update. I checked it and it works fine for me.

**Comment by YilianSource** [comment]
Awesome! Thanks again for using the library and sorry for the inconvenience!

**Comment by zitrone475** [comment]
I think I found an error: In some places your code still references the party object even though it no longer exists in the new version. For example:

```
shape: party.array(["square", "rectangle"]),
count: party.variation(40, .5),
spread: party.constant(80),
size: party.variation(10, .8),
velocity: party.variation(-300, 1),
angularVelocity: party.minmax(1, 6)
```

**Comment by YilianSource** [comment]
Ah, that's a very good point. I forgot about those, shame on me for not testing properly.

I'll probably update it again this afternoon, and refactor a bit probably.

**Comment by YilianSource** [comment]
Alright, everything should be in order with v1.0.3 now!

**Comment by zitrone475** [comment]
Looks good again, thank you very much for your work!
