### ISSUE TITLE
More than an issue it may be a Suggestion to improve something I need to use and maybe others like me.

### ISSUE THREAD

**Issue by theghost1980** [YilianSource/party-js#22]
Hi there @YilianSource  first of all I hope you may be great.  I really like the library. It is a great asset.

Right now I'm working in a website and I would like to use it, in order to "celebrate the new users whom joined the NewsLetter".

**The issue I'm having is:** I cannot set the z-index property for the animation. 

I have tried modifying the parent element's z-index property. For example, this is the jsx code while using react & gatsby:
```
<div className="coloredScreenBGFixed">
       <div className="subcriptionCont" id="confettyDiv">
             ...some other elements
             and here below the button to test the library by executing the click event:
             <div id="my-button"  onClick={() => party.screen()}>
                   Click me!
             </div>
       </div>
</div>
```
The CSS file shows the properties z-index of all parent's as:
`z-index: '99999'`
Because I use the descendant way in all my websites to maintain order.
Which means I set 99999 for the element to be on top, and all the rest 99990, 99980...you get the point for sure.

_**I can see the particles are emitted only on the same z-index = 0. I have done some tests and if I set all the divs to a z-index = 0, the particles show on top which is fine.**_

**The problem is** 
what happen if I need to render the confetti on top of everything? 
I have set the parent for this div as absolute with z-index: 99999(my higher value), but I cannot find a way to set the confetti to be on top of that, in fact so far I wasn't able to find any way to set this property at all.
Could be possible to add this feature? Ot let me know how could I solve this in order to be able to set the z-index property of the animation itself. The code inside of party.min.js is kind of heavy to modify also when someone doesn't knows it.

If you let me and tell me how? I could modify the property and help you out by issuing a pull request? 

Maybe other people can find this useful when they need to render on top of the body or something else?

Please let me know I have explained myself or If you need more info. I would really appreciate the help so I can use the library. Thanks.

A pic from this in action: [Click to see how the particles stay on the lower z-index](https://ibb.co/rpVq7vV)

**Comment by YilianSource** [comment]
First of all, glad you're enjoying the library! Thank you so much for the detailed issue description. It's true, I haven't experimented with multiple z-indices during development, an oversight on my end.

To explain a bit what's going on: the library creates a canvas element inside the DOM, with some default styling applied.
https://github.com/YilianSource/party-js/blob/master/party.js#L690

I'm not sure how to handle this in the best way for everyone, since different users might need different z-indices. I might try finding a workaround to have it always overlaid on top, I'll see about that.

In the meantime, you could try this: the canvas element has the ID `party-js-canvas`, you could add the z-index yourself in your stylesheet:
```css
#party-js-canvas {
    z-index: 99999;
}
```

Let me know if that helped you!

**Comment by theghost1980** [comment]
Hi there @YilianSource thank you so much for answering to me so fats and also for the help.

After testing the solution you gave me, the library works perfect.
So basically what I did was apply the css style as you told me:
```
#party-js-canvas {
    z-index: 99999;
}
```
I wrote this code inside of the css main file I'm using in my project. And it worked like a charm.
Suggestion: If you think to apply this as a new feature, it may be good idea to define the z-index as a root variable on top, something like:
```
/* variables */
:root {
    /* components */
    --var-zIndex-party: 99999; //default z index position
    /* end components */
}
```
Then inside the javascript component you could use the props as the user define them, let's say:
props.zIndex="10000" or props.zIndex="default" and then you could just change the var of the root document so it will change the property of the DOM element.

I will left some screenshots of the component working perfectly after the modifications you told me to do.
Thank you so much.

[Image 1](https://ibb.co/tZ4Nwkw)

[Image 2](https://ibb.co/tDWvjvs)
