### ISSUE TITLE
Examples in the documentation do not work

### ISSUE THREAD

**Issue by MrOttimista** [yiliansource/party-js#26]
In docs ( example page ) `https://partyjs.yiliansource.dev/docs/examples` 
the buttons `Try out ` does not do any action

![image](https://user-images.githubusercontent.com/40366999/114567865-eb6ea080-9c73-11eb-8551-63a9d54af50d.png)

**Comment by YilianSource** [comment]
Ah yes, it seems this is because of the swift loading feature of Docusaurus. As a workaround, try reloading the page, this will activate the buttons.

I'm currently working on v2 of the library, where the docs will be redone and this will be fixed.

**Comment by MrOttimista** [comment]
it is working 
thanks

**Comment by TimNZ** [comment]
@YilianSource  Examples removed?

**Comment by YilianSource** [comment]
> @YilianSource Live examples removed/disabled on https://partyjs.yiliansource.dev/?

Yeah, with the release of v2 of the library I had to rewrite the docs, which means that the old examples no longer apply. I will work on new examples in the docs over the following days!
