### ISSUE TITLE
Documentation examples/demos

### ISSUE THREAD

**Issue by yiliansource** [yiliansource/party-js#30]
**Is your feature request related to a problem? Please describe.**
Currently the v2 documentation does not feature any examples on how the library looks in action. This makes it hard to get an idea of how to implement certain effects, and what they will look like.

**Describe the solution you'd like**
A subcategory of the documentation with samples. They could include:
- Particles on button click
- Confetti on drag (hold)
- Custom SVG particles
- (more to come...?)

Feel free to suggest more desired examples!

**Comment by deefour** [comment]
I'd strongly suggest making the homepage actually use party-js, even before fleshing out docs examples.

**Comment by nikola1970** [comment]
Please add some exaples indeed. There is not much value without them! I have no idea how this looks like even though I suspect it might be nice.

**Comment by J1marotta** [comment]
Came here to say this as well, it's not a party(.js) if you're not showing it off

**Comment by jezmck** [comment]
I too was looking for a demo.

(tags: demos, demonstration, demonstrations, example, examples)
