### ISSUE TITLE
Website busted on Safari

### ISSUE THREAD

**Issue by peterbe** [yiliansource/party-js#32]
**Describe the bug**
Opened https://partyjs.yiliansource.dev/ in Safari 
Can't scroll down to check out the demos.

**To Reproduce**
1. Open Safari 
2. Go to https://partyjs.yiliansource.dev
3. Try to scroll down

**Expected behavior**
Be able to scroll down. 

**Enviroment**
- [ ] Safari

**Additional context**

I can't take a screenshot of the fact that I can't scroll, but this is what it looks like. 
<img width="1616" alt="Screen Shot 2021-04-19 at 10 12 28 AM" src="https://user-images.githubusercontent.com/26739/115250869-fa33d800-a0f7-11eb-8b53-f2358ee4a1e2.png">

**Comment by peterbe** [comment]
PS. The reason I even tried was that the demos didn't work when I opened on Safari on my iPhone so I wanted to test on my desktop (macOS) computer. Worked fine in Firefox. Tried desktop Safari and thus discovered this.

**Comment by peterbe** [comment]
Oh, it might not be related to Safari. I opened the web console in my Firefox and that changed the viewport height. Now I can't scroll in Firefox either. 
<img width="1616" alt="Screen Shot 2021-04-19 at 10 15 47 AM" src="https://user-images.githubusercontent.com/26739/115251207-5139ad00-a0f8-11eb-83e1-b80aaade9639.png">

**Comment by yiliansource** [comment]
Hey, thanks for the issue! I'm sorry for the inconvenience. I recently upgraded the docs to v2 of the library, which is in pre-release now. In hindsight, this might've been a bit too early. I'll try to get examples for v2 out over the next couple of days (#30).

**Comment by peterbe** [comment]
PS. I filed this issue because I first noticed the demos didn't work on Safari iOS. So I tested on desktop Safari and then I hit a bug with the webpage itself. 
But now I can see that independent of the website, the demos work great in Safari iOS! 🎉

**Comment by yiliansource** [comment]
Glad you like them! 🎉
