### ISSUE TITLE
Missing Meta Description

### ISSUE THREAD

**Issue by lucasstarsz** [yiliansource/party-js#33]
## Describe the bug
The meta description in the embed produced by any links to the homepage are the default description still.

## To Reproduce
1. Paste the link into any chat service, such as Discord or Guilded

## Expected behavior
Your own description of your amazing project!

## Additional context
This is how it currently looks:
![image](https://user-images.githubusercontent.com/64715411/115262762-d4f89700-a102-11eb-911b-39270c7eeac5.png)

You'll find the place to change it here:
https://github.com/yiliansource/party-js/blob/db71bc56080b3ea674827b343a028ca145e3583e/docs/src/pages/index.js#L116

**Comment by yiliansource** [comment]
Thanks for reporting this, it will be implemented together with #28.

**Comment by lucasstarsz** [comment]
Thanks! I completely missed that other issue, my bad.
