### ISSUE TITLE
Online demos

### ISSUE THREAD

**Issue by jcubic** [yiliansource/party-js#36]
**Is your feature request related to a problem? Please describe.**
There is no way to test the library, there is no real demo that shows how it looks like, it requires cloning the repo to see how it works.

**Describe the solution you'd like**
Publish samples on the website so users can see how the library works.

**Describe alternatives you've considered**
I've searched and was not able to find any demo, I don't want to clone the repo to see how it works.

**Comment by yiliansource** [comment]
There's been a strong demand for this (#30, #32) and I'll get to it ASAP. Not adding them right away when pre-releasing v2 admittedly was an oversight on my end. I'll probably manage to add them today or tomorrow.
