### ISSUE TITLE
party.screen() no longer works in 2.0

### ISSUE THREAD

**Issue by steveschmitt** [yiliansource/party-js#41]
Had to go back to 1.0.3

**Comment by yiliansource** [comment]
This is something I had not thought of, thanks for the report! Version 2.0 is out as a pre-release at the moment, so I still have time to fix these things. The method was removed in favour of template methods and better export organisation.

Do you have a suggested way of implementing this? Or should a method by the same name be implemented for compatibility?

**Comment by steveschmitt** [comment]
Compatibility is nice, but since you are going to 2.0, it is okay to change the interface (as long as it is documented).

The important thing is that the functionality is still there.

**Comment by yiliansource** [comment]
All right, I'll add it as a TODO in #39, and discuss the migration in #29. Thanks for the tip!
