### ISSUE TITLE
'import party from "party-js"' not working in TypeScript

### ISSUE THREAD

**Issue by peterbe** [yiliansource/party-js#48]
**Describe the bug**

This does NOT work:
```javascript
import "./styles.css";
import party from "party-js";
// const party = require("party-js");

export default function App() {
  return (
    <div className="App">
      <h1 onClick={(e) => party.confetti(e.target)}>Party!</h1>
    </div>
  );
}
```

This WORKS:
```javascript
import "./styles.css";
// import party from "party-js";
const party = require("party-js");

export default function App() {
  return (
    <div className="App">
      <h1 onClick={(e) => party.confetti(e.target)}>Party!</h1>
    </div>
  );
}
```
The error you get is:

```
TypeError
can't access property "confetti", _partyJs.default is undefined
```

**To Reproduce**
1. Go to https://codesandbox.io/s/nostalgic-breeze-s5uwv?file=/src/App.tsx
2. Click on the H1 heading
3. See error

**Expected behavior**
An error shouldn't happen.  :)

Note, if you change the import to `const party = require("party-js");` instead, then it works. 

But if I do that my `eslint` is barking at me. :)
```
error  Require statement not part of import statement  @typescript-eslint/no-var-requires
```

**Enviroment**
- [x] Browser
- [ ] Node.js
- [ ] Other

**Additional context**

Test and experiment on: https://codesandbox.io/s/nostalgic-breeze-s5uwv?file=/src/App.tsx:56-90

My project where this came up was a Preact-cli TypeScript app but the above sandbox fully demonstrates it too.

**Comment by yiliansource** [comment]
Try:

```ts
import * as party from "party-js";
```

I may have forgotten to change that somewhere in the docs, which guide did you follow?

Do you think that the library should use the default export instead?

**Comment by peterbe** [comment]
> I may have forgotten to change that somewhere in the docs, which guide did you follow?
> 

I have no idea. Perhaps I assumed. 
https://party.js.org/docs/#browser clearly demonstrates the form you suggested. 

> Do you think that the library should use the default export instead?

Not sure. I know with `React` you can do `import React from 'react'` **and** `import * as React from 'react'`. 
Not sure how that works but it would be nice to get both forms working to avoid confusion like my own. 

When I look at my various JS projects that uses modules, the common form is almost always `import thing from 'name'`.

**Comment by peterbe** [comment]
I know so very little about UMD and all the hacks that poor library-creators have to copy and paste. But, at the moment, I can no longer server-side render my preact-cli and TypeScript project because of the  `import * as party from "party-js";` line. 

With `preact-cli`, it can Node SSR render a couple of pages from the single-page-app so that they render a bit faster. The code that actually calls `party.confetti(...)` is never called during this but the complaint I get is on the `import * as party from "party-js";` line :(

<img width="871" alt="Screen Shot 2021-05-03 at 9 15 39 AM" src="https://user-images.githubusercontent.com/26739/116880565-28cdaa80-abf0-11eb-823f-e7c206fd7494.png">

I don't know how other projects solve this but perhaps we can find a standard export block blob that we can use.

**Comment by yiliansource** [comment]
I'll take a look, maybe I can get both to work without any major tradeoffs. I agree that the following just looks nicer than a wildcard import:

```ts
import party from "party-js";
```

> I know so very little about UMD and all the hacks that poor library-creators have to copy and paste.

Me neither actually, the TypeScript compiler handles most of it, but it seems like there's still some stuff left for me to do! :)

> But, at the moment, I can no longer server-side render my preact-cli and TypeScript project [...]

SSR was something that I didn't think of at first, and I only stumbled over it while actually writing the docs for the library, as those are a SSR SPA aswell. I actually wrote a fix for it a bit ago (using `Lazy<T>`s, so the feature set is only activated once used), but it's not deployed to npm yet, since I wanted to wait with the proper 2.0.0 release until #39 and #29 are done.

As a general workaround when using SSR, you can use the following:

```ts
let party = {}; // you can mock any calls you might need here.
if (document && window) {
    const party = require("party-js");
}

// lateron you can use the import here, but make sure none of the code is called at SSR time.
```

**Comment by peterbe** [comment]
If I use `require("party-js")` my `eslint` will yell at me :)
But, yeah, I can use that as a desperate work-around for now.

**Comment by yiliansource** [comment]
Yeah, I'm sorry for that, I should've thought of it earlier.

I'll try to find time to finish up v2 soon, so you can safely import it using ES6 syntax without having it yell at you! :)

**Comment by yiliansource** [comment]
@peterbe I just merged the major v2 changes into the main branch, including the SSR fix and the default import. I'm planning on officially releasing v2 in a couple of days, after I implement the rest of the things on my TODO list. Stay tuned! :)
