### ISSUE TITLE
party.confetti does not work in Angular

### ISSUE THREAD

**Issue by horuko** [yiliansource/party-js#53]
**Describe the bug**
party.confetti does not work in Angular. I try to install the library by download from jsdelivr and install from package.json and the results is the same.
When I install the library by download from jsdelivr, if I get party object in debug mode just after download the library, I see confetti function, but not when I use in any component.

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-test-party?file=src%2Fapp%2Fapp.component.ts
2. Click on click me!
3. party.confetti does not work but party.screen does

**Expected behavior**
both party.confetti and party.screen work.

**Enviroment**
- [ ] Browser
- [ ] Node.js
- [  X ] Angular 9 / 11

**Additional context**

**Comment by yiliansource** [comment]
Might be that you're still on v1.x. v2 is currently in pre-release, you're free to use it but the API may still drastically change. It's planned to properly release in a few days though (if I can manage)!

**Comment by yiliansource** [comment]
@horuko just tested it out using the demo project, thanks!

The pre-release initally had the syntax `import * as party from "party-js"` to impor the library. When v2 is finally released, this will no longer be supported, hence the docs, I apologize for the confusion.

`party.screen()` was a 1.x only method. To learn how to reproduce it with v2, check out the [migration docs](https://party.js.org/docs/migrating-v1-v2), although the syntax given is not released on npm.

**Comment by yiliansource** [comment]
@horuko Is this resolved? :)
