### ISSUE TITLE
Support for mobile?

### ISSUE THREAD

**Issue by JeswinSunsi** [yiliansource/party-js#64]
Hey, is there support for mobile browsers too? I've been trying ```ontouchstart="party.confetti(this)" onclick="party.confetti(this)"``` and it is not working.

**Comment by yiliansource** [comment]
The library should work just fine on mobile devices, last time I checked the samples on the website were functional on mobile. Can you elaborate on "not working", are there any console errors?

**Comment by yiliansource** [comment]
@JeswinSunsi Is this resolved? Did you manage to get it working on mobile?
