### ISSUE TITLE
Dynamic importing of party-js

### ISSUE THREAD

**Issue by Bandit** [yiliansource/party-js#69]
Guess I'm doing something wrong here, but why do I need to do this `module.default.default` thing to get a dynamic import to work? (This is Sveltekit code)

```js
    onMount(async () => {
        if (confetti && browser) {
            const module = await import("party-js");
            const party = module.default.default;
            
            party.confetti(el, {
                count: party.variation.range(20, 40),
            });
        }
    });
```

**Comment by yiliansource** [comment]
Hey there, sorry for the very late response, have been dealing with some health issues recently.

What version of the library are you on? I remember moving some stuff around, might have accidentally broke something with imports.

**Comment by Bandit** [comment]
`2.0.1`

**Comment by yiliansource** [comment]
Weird issue. I'm not familiar with how exactly async importing in Svelte works, [but this minimal example works without the `default`s](https://codesandbox.io/s/peaceful-lehmann-1vpjn?file=/src/App.js). Can you maybe check what the return type of the import statement is?

**Comment by Bandit** [comment]
Thanks for looking into this - just a heads up that I'm really busy on some other things. Will come back to this and re-open it with more detail / example repo 👍
