### ISSUE TITLE
party.js container does not take the enitre height of the body

### ISSUE THREAD

**Issue by dk-raw** [yiliansource/party-js#71]
**Describe the bug**
The `party-js-container` does not spread to the entire height of the body causing the confetti to get cut off in a straight line. 

https://www.mathflare.xyz/#donate 

![image](https://user-images.githubusercontent.com/68110106/133125336-5794f326-f2b6-49bc-9bc9-27c7e54a87f6.png)

https://user-images.githubusercontent.com/68110106/133125690-2f8c5fd6-3ab2-42fa-9387-416d6a409e0e.mp4

**Environment**
Latest stable Firefox and latest stable ms Edge on Windows 10 pro

**Comment by yiliansource** [comment]
Hey there, sorry for the late response. It seems like the container has some trouble calculating the full height it needs to cover; I'll look into it and get back to you.

**Comment by yiliansource** [comment]
I hope this is fixed now; I'll roll out a new version later today or tomorrow with the fix!

**Comment by yiliansource** [comment]
I just published `v2.1.0`, this should make it work! 😄

**Comment by dk-raw** [comment]
Great! Seams to work now. Thanks for fixing the issue and keep up the excellent work!!!
