### ISSUE TITLE
Ability to control "range" (radius)

### ISSUE THREAD

**Issue by peterbe** [yiliansource/party-js#72]
**Is your feature request related to a problem? Please describe.**

In the `party.sparkles()` I can control size, count, etc. But I can't control the range at which how far the stars go from the epicenter. It would be nice to have a configuration for that. 

**Describe the solution you'd like**

Perhaps
```js
party.sparkles(target, {radius: party.variation.range(100, 150) })
```

**Comment by yiliansource** [comment]
Hey there!

This is already possible by customizing the source sampler of the effect. Instead of emitting from the cursor, you can create a `Circle` sampler, like such:

```js
(e) => party.sparkles(new Circle(e.clientX, e.clientY, 100))
```

Note that this requires the event `e` to be a mouse event. Or did you mean that you want to generically inflate the target's bounding box by a certain radius?

I put together a short demo for your reference: https://codesandbox.io/s/clever-napier-67166?file=/src/App.js

**Comment by peterbe** [comment]
> Or did you mean that you want to generically inflate the target's bounding box by a certain radius?

Yeah. That. Basically reducing the total distance that the little stars travel across the screen.

**Comment by yiliansource** [comment]
So essentially something like this?

![image](https://user-images.githubusercontent.com/41469451/134807729-f46a863c-2901-404d-afba-491ababeef68.png)

What do you mean by total distance?

**Comment by peterbe** [comment]
<img width="720" alt="Screen Shot 2021-09-26 at 10 07 26 AM" src="https://user-images.githubusercontent.com/26739/134811315-1b3f13e3-7ad3-4c39-b8cb-15f7bc1df5d3.png">
I tried to take a screenshot just as the furthers stars started fading. Then I drew a maroon/red circle at that point. 
What I which is that that max outer circle only made to to the green circle instead. "Max blast radius" perhaps?

**Comment by yiliansource** [comment]
Ahh, I see now, you want to control the maximum distance they travel. This is a great idea - for some reason I didn't think about exposing the `lifetime` parameter of the template. Would be prefer both `lifetime` and `speed` to be exposed, so you can adjust them individually, or would you prefer one of them plus a `maxBlastRadius` field?

**Comment by peterbe** [comment]
> Ahh, I see now, you want to control the maximum distance they travel. This is a great idea - for some reason I didn't think about exposing the `lifetime` parameter of the template. Would be prefer both `lifetime` and `speed` to be exposed, so you can adjust them individually, or would you prefer one of them plus a `maxBlastRadius` field?

Yes :)

(speed is already an option I believe, and it's documented too)

Honestly, I don't know. I animate the sparkles on the checked off checkboxes in a to-do-list looking application. I just wanted the sparkles to originate from where the checkbox is on each row of the list. But it just goes too far away from that. 

In my particular case, I think a `maxBlastRadius` (e.g. `maxBlastRadius: 300` for 300px) would be super convenient.

**Comment by yiliansource** [comment]
`maxBlastRadius` it is then! :)

But in what way would you expect the particles to be adjusted? Should they (1) go slower and live longer, or (2) go faster and live shorter? All in order not to exceed the `maxBlastRadius`.

**Comment by peterbe** [comment]
> `maxBlastRadius` it is then! :)
> 
> But in what way would you expect the particles to be adjusted? Should they (1) go slower and live longer, or (2) go faster and live shorter? All in order not to exceed the `maxBlastRadius`.

live shorter. 

But that might just prove a point. If instead of a `maxBlastRadius`, since I can already control the speed, if we can just add an option to control the "lifetime" I can use speed and lifetime to create the effect of a smaller blast radius. No?
