### ISSUE TITLE
Doesn't seem to work on Windows Remote Desktop (RDP) Windows Server 2019 session

### ISSUE THREAD

**Issue by Patrick-HSO-Innovation** [yiliansource/party-js#81]
**Describe the bug**
When opening the Party demo site ( https://party.js.org/ ) in an RDP session, the confetti does not seem to work.

**To Reproduce**
Open a windows RDP session
goto https://party.js.org/ 
use " try it out "

**Expected behavior**
I would really really really really really like to have working confetti on my RDP box :-D

**Environment**
Chrome (latest)
Windows Server 2019

**Additional context**

**Comment by yiliansource** [comment]
I'm afraid I'm not familiar with RDP at all.

Maybe it's because the `prefers-reduced-motion` media query is active in remote sessions? Are there any console errors on the remote session?

**Comment by Patrick-HSO-Innovation** [comment]
You are correct!

For future readers: the "show animations in Windows"  _ease of access_ option is _disabled_ by default in a _remote desktop session_.

**Comment by yiliansource** [comment]
Awesome!

Out of curiosity, where do you feel like this should've been documented, for you to more easily find a hint to it?

**Comment by Patrick-HSO-Innovation** [comment]
I'm really not sure if the `prefer-reduced-motion` is supposed to be basic knowledge of JS developers :-)

But if it isn't a note under the "try me" box on the party.js.org site might be a good place?

Somthing like:

Note:  If you don't see the neat little sparkles show up in your browser, and you are sure you're on the latest version, you might try alter the [prefer-reduced-motion settings](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)

Something like that?
