### ISSUE TITLE
Error: Cannot find module '/home/xxxx/party-js/lib' in Next JS

### ISSUE THREAD

**Issue by Santosl2** [yiliansource/party-js#89]
**Describe the bug**
When i add party JS to my project, in first time this works ok, but if i reload the page, this the error appear for me
![image](https://user-images.githubusercontent.com/67132916/175176300-dd6daa58-87f1-405c-abee-9aa95be2819b.png)

**To Reproduce**
- Add party-js lib
- import to your project
- implements the party js
- reload the page

My code:

![image](https://user-images.githubusercontent.com/67132916/175177068-adbab875-4391-4607-8b80-4411cc77364e.png)

![image](https://user-images.githubusercontent.com/67132916/175177048-5a879adb-5593-4fca-8ba3-2533f2d6cc8e.png)

**Expected behavior**

**Environment**

**Additional context**
- Next JS -> 12.1.6
- React and react-dom -> 18.2.0
- react-redux -> 8.0.2
- redux-persist -> 6.0.0

**Comment by yiliansource** [comment]
Can you give some additional context? What version are you on, which framework are you using?

**Comment by yiliansource** [comment]
I can reproduce it, but I can't figure out what's causing it, since it's working fine for non-Next.js apps.
I'll look into it more once I have more time on my hands.

**Comment by Santosl2** [comment]
Okay! Thanks.. I'm waiting for you

**Comment by yiliansource** [comment]
Hi, this should be fixed in #91 with `v2.2.0`, let me know if upgrading works out for you.

**Comment by Santosl2** [comment]
Nice! I will try here

**Comment by Santosl2** [comment]
@yiliansource problem solved!
