### ISSUE TITLE
Adding webpack dev server to optional dependencies triggers it to be installed by consumers of the package

### ISSUE THREAD

**Issue by mikewesthad** [yiliansource/party-js#90]
**Describe the bug**

Hi! I was playing around with using Party.js in a yarn / next project, and installing the lib (`yarn add party-js`) triggers a whole mess of installed dependencies because `webpack-dev-server` is expressed as an optional dependency (see snippet below). I'm on yarn v1.22.17, so `yarn add party-js --ignore-optional` doesn't work. Is there a reason why webpack dev server is set up as an optional dependency? It seems like it should be a dev dependency [so I moved it there on a fork](https://github.com/mikewesthad/party-js/commit/80e6edc114b4193ee26638c5c9144048a0cf91f7) so that I could install something without triggering an install of webpack dev server.

Thanks!

```
info Direct dependencies
└─ party-js@2.1.3
info All dependencies
├─ @leichtgewicht/ip-codec@2.0.4
├─ @types/bonjour@3.5.10
├─ @types/connect-history-api-fallback@1.3.5
├─ @types/http-proxy@1.17.9
├─ @types/serve-index@1.9.1
├─ @types/sockjs@0.3.33
├─ ansi-html-community@0.0.8
├─ bonjour-service@1.0.13
├─ connect-history-api-fallback@1.6.0
├─ default-gateway@6.0.3
├─ define-lazy-prop@2.0.0
├─ detect-node@2.1.0
├─ dns-equal@1.0.0
├─ dns-packet@5.4.0
├─ faye-websocket@0.11.4
├─ fs-monkey@1.0.3
├─ handle-thing@2.0.1
├─ hpack.js@2.1.6
├─ html-entities@2.3.3
├─ http-deceiver@1.2.7
├─ http-parser-js@0.5.8
├─ http-proxy@1.18.1
├─ is-docker@2.2.1
├─ is-wsl@2.2.0
├─ memfs@3.4.7
├─ multicast-dns@7.2.5
├─ obuf@1.1.2
├─ open@8.4.0
├─ party-js@2.1.3
├─ require-from-string@2.0.2
├─ select-hose@2.0.0
├─ selfsigned@2.0.1
├─ serve-index@1.9.1
├─ sockjs@0.3.24
├─ spdy-transport@3.0.0
├─ spdy@4.0.2
├─ thunky@1.1.0
├─ wbuf@1.7.3
├─ webpack-dev-middleware@5.3.3
├─ webpack-dev-server@4.9.2
├─ websocket-driver@0.7.4
└─ websocket-extensions@0.1.4
Done in 8.60s.
```

**To Reproduce**

**Expected behavior**

**Environment**

**Additional context**

**Comment by yiliansource** [comment]
> Is there a reason why webpack dev server is set up as an optional dependency?

That was probably a mistake/oversight on my end, or there was some weirdness going on with dependencies. I'll check it out, but v3 will not use it anyway. Thanks for the notice!
