### ISSUE TITLE
Question: how to change effect (raining down instead of going up first)

### ISSUE THREAD

**Issue by alexluong** [yiliansource/party-js#95]
Hi there, first all of I really appreciate the thoughts and efforts you've put into this library. It has definitely shown through with the documentation and the codebase.

However, even with the docs I'm still having a hard time customizing the effect. I would like to create an effect where the confetti just rains down from the top of the screen instead of the default effect.

I tried going through the docs and trying out the code in "create custom emitter" page but still have quite a bit of a hard time getting things to work.

I'd appreciate a bit more guidance on this if possible. Thanks!

**Comment by yiliansource** [comment]
Hey there! Sorry for the late response on this.

A lot of people seem to be having trouble with the docs, I hope I can get around to rewrite them to be more clear sometime (soonish). I also want to rewrite the library's API design, so it's a bit more intuitive to use.

That being said, I think this should be along the lines of what you wanted to achieve?
https://codesandbox.io/s/zen-ganguly-2y8xcs?file=/src/index.ts

I'd be happy to answer more questions you have, enjoy the effect!

**Comment by alexluong** [comment]
Hi there, thanks for getting back to me. The codesandbox is a great starting point for me to tinker with. The general effect is very similar to what I'm trying to do. Will get back to you if there's anything else. Appreciate your work and look forward to seeing the next iteration of the library API.

**Comment by yiliansource** [comment]
Glad you're enjoying it!
