### ISSUE TITLE
PartyJS does not work - possibly OS-specific?

### ISSUE THREAD

**Issue by pokrovskyy** [yiliansource/party-js#97]
A super-specific & weird bug - PartyJS does not work on my machine. None of the browsers (Google Chrome 106, Safari 13.1, Firefox 105). Mac OS Catalina 10.15.7. Trying on your demo website https://party.js.org. What could be the reason and where to look? No errors show in the console. It does work on virtual machine (Parallels Desktop Windows 10) It worked before (like a year ago for sure) Nothing really changed in my setup except FileVault enabled 😄 

The only notable difference when I look on the page is - when I click on the test surface on party.js.org - I do not see the `party-js-particles` div added under the `party-js-container` (I see it on the virtual machine where it works well) 

Seems OS-specific but how could that be?

**Comment by yiliansource** [comment]
And there's nothing in the console indicating an error? Weird. As this is meant to run in browsers, there shouldn't be anything OS-specific. Note that the `party-js-container` is lazily instantiated once required.

**Comment by pokrovskyy** [comment]
thanks for the reply @yiliansource . That's the thing - no errors / messages in the console. And what's most confusing that it's persistent across all browsers on my macOS, but works on Parallels Desktop Windows 10 virtual machine 🤷

**Comment by yiliansource** [comment]
Can you check if the [`(prefers-reduced-motion)` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) is active? The library is deactivated by default when this is active.

**Comment by alex-zach** [comment]
On my machine (MacBook Pro 14" 2021, macOS 13.0) PartyJS works in Safari 16.1 (18614.2.9.1.12) and Chrome (107.0.5304.110).

**Comment by pokrovskyy** [comment]
@yiliansource wow mystery solved! This is my specific setup issue - I turned on "Reduce motion" in my macOS > Accessibility (I prob have >20 displays over 4 monitors going simultaneously, and this feature allows for quicker transition when time is of the essence) Once I unchecked it - it instantly started working 👍  So it's not a bug - closing the issue.

![CleanShot 2022-11-17 at 10 20 04@2x](https://user-images.githubusercontent.com/1635058/202526549-aedb1f6a-4b10-4858-8691-4eb661e5949f.png)

**Comment by yiliansource** [comment]
Ah, glad we solved it!

I should probably add this to a FAQ or common issues list - I'd imagine that this is not as intuitive to developers as you might expect. Do you think the library should log a message in the console when deactivated through that media query?

**Comment by pokrovskyy** [comment]
As you can tell, that definitely would have helped debugging this 😄 Console message even more important than the docs imo. devs look into the logs first when something does not work, and then go study docs haha 😎

**Comment by yiliansource** [comment]
Alright, I opened a new issue for it, thank you for your thoughts!
