### ISSUE TITLE
Adding settings

### ISSUE THREAD

**Issue by jasonhoward64** [yiliansource/party-js#98]
Hi there,

Great js package!

I was wondering if you could help me. I'd like to set the z-index on my confetti. I'm using the following code block.

            party.confetti(this, {
                count: party.variation.range(40, 80),
            });

Thanks!

**Comment by yiliansource** [comment]
Hey there!

You can modify the z-index of the scene with
```ts
party.settings.zIndex = /* ... */;
```
which you only need to set _once_ during the start of your application.

Refer to https://party.js.org/docs/ref/configuration.
